# GitHub Pages 配置文件

# 网站基本信息
title: "张贤平 - 个人主页"
description: "张贤平的个人主页，展示项目作品和技术博客"
author: "张贤平"
email: "contact@zhangxianping.com"
url: "https://zhangxianping.github.io"
baseurl: ""

# GitHub Pages 设置
theme: 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: Asia/Shanghai

# 包含和排除文件
include:
  - _pages
  - assets

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github

# 社交媒体链接
social:
  github: zhangxianping
  email: contact@zhangxianping.com
  linkedin: 
  twitter: 

# SEO 设置
lang: zh-CN
google_analytics: 

# 网站导航
nav_pages:
  - title: "首页"
    url: "/"
  - title: "项目"
    url: "/projects.html"  
  - title: "博客"
    url: "/blog.html"

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"